config/routes.rb
Bootstrap::Application.routes.draw do

  get "/invites/:provider/contact_callback" => "invites#index"
  get "/contacts/failure" => "invites#failure"
  
  get "/invites/index"
  get "/contacts/yahoo/callback"
  
  resources :invites
  resources :alumnisearches
  resources :advancesearches

  
  
  get "users/show"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,:registrations => "registrations" }

  resources :friendships, :controller => 'friendships', :except => [:index, :show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end

  resources :posts, only: [:create,:index , :destroy]

  resources :posts do
    resources :comments, :only => [:create]
  end

  get "secure/index"

  get "secure/index"

  get "home/index"

  get "home/agreement"
  get "home/default"
  get "home/whatislinkedin"

  
  get "users/join"

devise_for :users, :controllers => {:sessions => 'devise/sessions'}, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'register' => 'devise/registrations#join', :as => :new_user_registration
    get 'sign_up' => 'registrations#new', :as => :new_user_registration
    get 'sign_up' => 'registrations#new', :as => :new_user_registration
    get 'all'     =>  'users#index'
    get 'users/:id' => 'users#show'
    get 'invitations' => 'users#friendrequests'
    get '/users/auth/facebook' => 'users/omniauth_callbacks#facebook'
  end

  
  resources :users

  get 'users/:id/edit2' => 'users#edit'

authenticated :user do
  root :to => "home#index"
end

devise_scope :user do
  root to: "registrations#new"
  
end

match 'home/index' => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :user_roles, :through => :authorizations

  has_many :posts , dependent: :destroy
  has_many :comments , dependent: :destroy
  has_many :friendships 
  has_many :friends, :through => :friendships

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, , :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable
    


  devise :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :userLname,:userFname,:email, :password,:image, :country ,:postelCode ,:persontype , :selfemployeetype , :adult  , :DOB  , :currentPosition , :JobTitle,:Company,:Industry,:timepperiodfrom,:timeperiodto,:University,:universityStart,:universityEnd , :password_confirmation,:current_password, :remember_me, :authentication_token,:provider, :uid, :name
  alias_attribute :roles, :user_roles

  #Image Uploader ( A great gem with a lot of tools)
  mount_uploader :image, ImageUploader


  # A good tool to model friends request , friend list and etc etc 
  include Amistad::FriendModel



  # Ensure the there is a auth token for all users, authorization will still be enforced
  before_save :ensure_authentication_token


  # CLient Side  Validations via client_side_validations

  validates_presence_of :userLname , :userFname , :email , :password

  validates_length_of :password , :minimum => 6

  validates_confirmation_of :password



  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  
  # Define user role methods
  def role?(role)
    role_names.include? role.to_s
  end

  def role_names
    roles.map(&:name)
  end

  def ensure_authentication_token!   
    reset_authentication_token! if authentication_token.blank?   
  end  

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end


protected
  def confirmation_required?
    false
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  
  #include ActiveModel::ForbiddenAttributesProtection

  before_filter :authenticate_user!

  def index
    @users = User.search(params[:search])
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @users }
    end
    session[:return_to] ||= request.referer
  end

  # GET /users/1
  # GET /users/1.json
  

  def show
    @user= User.find(params[:id])
    @post = current_user.posts.build if signed_in?
    @postsbyuser = @user.posts
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user}
    end
  end


  # GET /feedbacks/1/edit
  def edit
    @user= User.find(params[:id])
  end


  def new    
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user}
      
      format.html { render :action => "edit" }

    end
  end


  def friendrequests
    @users = User.all()
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="actions">
    <%= f.submit 'Update', :class => ["btn","primary"] %>
    <%= link_to 'Cancel', users_path, :class => ["btn"] %>
  </div>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :email%>
    <div class="input">
      <%= f.text_field :email, :class => "xlarge" %>
    </div>
  </div>
   
<% end %>

app/views/users/_header_loggedin.html.erb
<div id="header_wrapper">
		<div id="the_header">
			<div id="left_child">
				<h1><a href="/" class="home"></a></h1>
				<div id="search_form">
					<%= form_for Advancesearch.new , :html=> { id: 'search_bar' } do |f|   %>
						<div id="type_background">
							<div class="styled_dropdown"></div>
						</div>
						<div id="search_box">
							<%= f.text_field :keywords , :id => "search_keywords" , :placeholder=> "Search for people, jobs, companies and more..."%>
						</div>
						
						<div id="advance_search">
							<%= f.submit '', :name=>"search", :id=>"search", :class => "search_bar_button" %>
							<a href="/advancesearches">Advanced</a>
						</div>
					<%end%>
				</div>

			</div>
			<div id="right_child">
				<ul id="notifications_area">


					<li class="notification_item" id="messages">
						<spam id="invitations_count"><%= current_user.pending_invited_by.count %></spam>

						<a href="/invitations">
							
						</a>



						<div class="activity_container" id="inbox">

							<div class="activity_drop">
								
								<div id="inbox_invitations">
									<div id="invitations_header">
										<h3>Invitations (<%= current_user.pending_invited_by.count %>)</h3>
									</div>
									<div id="invitations_container">
										<ol id="invitations">
											<% current_user.pending_invited_by.each do |u| %>
										      <li class="invitations_item">
												<a href="#">
													<%= image_tag u.image_url(:small).to_s %>
												</a>
												<div class="about_sender">
													<p>
														<%= link_to u.userFname+" "+u.userLname , u %>
													</p>
													<p>
														Professional
													</p>
												</div>
												<div id="action">
													<%= button_to "Accept", friendship_path(u,:user_id => u.id), :method => :put , :class => "accept" %>
	             									<%= button_to "Decline", friendship_path(u, :user_id =>  u.id), :method => :delete ,:class => "reject" %>
             									</div>
											  </li>
										    <% end %>
										</ol>
									</div>
								</div>
							</div>
						</div>
					</li>
					<li class="notification_item" id="notifications"><a href="#"></a></li>
					<li class="notification_item" id="add_connections"><a href="#"></a></li>
					<li id="profile_actions">
						<a id="profile_pic" href="#">
							<%= image_tag current_user.image_url(:small).to_s %>
						</a>
						<div id="account_nav">
							<div id="account_nav_options">
								<div id="account_nav_header">
									<h3>
										Account & Settings
										<span id="arrow"></span>
									</h3>
								</div>
								<div id="account_nav_body">
									<ul id="account_settings">
										<li id="self" class="account_settings_link">
											<span class="act_row">
												<span id="pic" class="act_icon">
													<%= image_tag current_user.image_url(:small).to_s %>
												</span>
												<span id="name" class="act_name">
													
													<%= link_to current_user.userFname+" "+current_user.userLname , current_user %>
												</span>
												<span id="signout" class="act_action">
													<%= link_to "Sign Out", '/users/sign_out'%>
												</span>
											</span>
										</li>
										<li class="account_settings_link">
											<a href="#">
												<span class="act_row">
													<span class="act_icon">
														<span id="upgrade" class="back_icons"></span>
													</span>
													<span class="act_name">
														Account: Basic
													</span>
													<span class="act_action">
														Upgrade
													</span>
												</span>
											</a>
										</li>
										<li class="account_settings_link">
											<a href="#">
												<span class="act_row">
													<span class="act_icon">
														<span id="job" class="back_icons"></span>
													</span>
													<span class="act_name">
														Job Posting
													</span>
													<span class="act_action">
														Manage
													</span>
												</span>
											</a>
										</li>
										<li class="account_settings_link">
											<a href="#">
												<span class="act_row">
													<span class="act_icon">
														<span id="language" class="back_icons"></span>
													</span>
													<span class="act_name">
														Language
													</span>
													<span class="act_action">
														Change
													</span>
												</span>
											</a>
										</li>
										<li class="account_settings_link">
											<a href="#">
												<span class="act_row">
													<span class="act_icon">
														<span id="settings" class="back_icons"></span>
													</span>
													<span class="act_name">
														Privacy & Settings
													</span>
													<span class="act_action">
														Review
													</span>
												</span>
											</a>
										</li>
										<li class="account_settings_link">
											<a href="#">
												<span class="act_row">
													<span class="act_icon">
														<span id="help" class="back_icons"></span>
													</span>
													<span class="act_name">
														Help Center
													</span>
													<span class="act_action">
														Get Help
													</span>
												</span>
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	<div id="main_nav_wrapper">
		<div id="main_nav">
			<ul id="user_nav">
				<li class="nav_item">
					<%= link_to 'Home', '/home/index' , :class=>"nav-link" %>
				</li>
				<li id="profile_nav" class="nav_item">
					<a id="profile" href="#" class="nav_link">Profile</a>
					<ul id="profile_sub_nav" class="sub_nav">
						<li class="nav_item">
							<%= link_to "Edit Profile", '/users/edit'  , :class=>"nav-link"%> 
						</li>
						<li class="nav_item">
							<a href="#">Who's Viewed Your Profile</a>
						</li>
					</ul>
				</li>
				<li id="networks_nav" class="nav_item">
					<a href="#" class="nav_link">Network</a>
					<ul id="networks_sub_nav" class="sub_nav">
						<li class="nav_item">
							<a href="#">Contacts</a>
						</li>
						<li class="nav_item">
							<a href="#">Add Connections</a>
						</li>
						<li class="nav_item">
							<a href="#">Find Alumni</a>
						</li>
					</ul>
				</li>
				<li class="nav_item">
					<a href="#" class="nav_link">Jobs</a>
				</li>
				<li id="interests_nav" class="nav_item">
					<a href="#" class="nav_link">Interests</a>
					<ul id="interests_sub_nav" class="sub_nav">
						<li class="nav_item">
							<a href="#">Companies</a>
						</li>
						<li class="nav_item">
							<a href="#">Groups</a>
						</li>
						<li class="nav_item">
							<a href="#">Influencers</a>
						</li>
						<li class="nav_item">
							<a href="#">Education</a>
						</li>
					</ul>
				</li>
			</ul>
			<ul id="business_nav">
				<li id="services_nav" class="nav_item">
					<a href="#" class="nav_link">Business Services</a>
					<ul id="services_sub_nav" class="sub_nav">
						<li class="nav_item">
							<a href="#">Post a Job</a>
						</li>
						<li class="nav_item">
							<a href="#">Talent Solutions</a>
						</li>
						<li class="nav_item">
							<a href="#">Advertise</a>
						</li>
					</ul>
				</li>
				<li id="last" class="nav_item">
					<a href="#" class="nav_link">Upgrade</a>
				</li>
			</ul>
		</div>
	</div>

app/views/users/friendrequests.html.erb
<link rel="icon" href="favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/stylesheets/ListingRequestsLeftDesign.css">
    <link rel="stylesheet" type="text/css" href="/stylesheets/home.css">
    <link rel="stylesheet" type="text/css" href="/stylesheets/friendrequests.css">
    <script src="/javascripts/home.js"></script>
    <script src="/javascripts/jquery.js"></script>
    <script src="/javascripts/advance_search.js"></script>

<% provide(:title, 'Invitations') %>
<%= render '/layouts/header_loggedin' %>

<section>
    <div id="BodyWrapper">
      <div id="MainBody">
        <div id="Search">
          <h2>
            Requests
          </h2>
        </div>
        
        
        
        <div id="results_col">
          <div id="results_count" class="mod results_count">
            <% current_user.pending_invited_by.each do |user| %>
              <% if current_user != user %>
	      		<% if user.invited? current_user  %>

              <ol>
                <li class="mod result idx0 people" >
                  <a href="#">
                    <%= image_tag user.image_url(:list).to_s %>
                  </a>
                  <div class="bd">
                    <h3>
                      <a class="title" href="#">
                        <strong class="highlight">  <%= user.userFname %></strong> <strong class="highlight"><%= user.userLname %></strong>
                      </a>
                    </h3>
                    <p class="description"><%= user.JobTitle %> at <%= user.Company %><%= user.University %></p>
                    <dl class="demographic"><dt>Location</dt><dd><%= user.country %></dd></dl>

                    <div class="srp-actions blue-button">
                      <div class="primary-action-button">
                        <div id="actionlist">
                          <%= button_to "Accept", friendship_path(user,:user_id => user.id), :method => :put , :class => "acceptold" %>
                                <%= button_to "Decline", friendship_path(user, :user_id =>  user.id), :method => :delete ,:class => "reject" %>
                              </div>
                      </div>
                    </div>
                  </div>
                </li>
              </ol>
              	<% end %>
              <% end %>
            <% end %>
          </div>
          
          <div id="results">
            <ul>
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/users/index.html.erb
<div class="container">
	<div class="row">

    

    <table id="user-table" class="zebra-striped">
      <tr>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @users.each do |u| %>
      <tr>
        <td><%= u.email %></td>
        <td><%= link_to 'Show', u %></td>
        <td><%= link_to 'Edit', edit_user_path(u) %></td>
        <td>

            <% if user_signed_in? %>
      <% if current_user != u %>
        <% if current_user.friend_with? u  %>
             
             <%= button_to "Remove", friendship_path(u, :user_id =>  u.id), :method => :delete %>
        
        <% elsif current_user.invited? u  %>
             
             <span class="btn btn-mini disabled">Pending</span>
             <%= button_to "Cencel", friendship_path(u, :user_id =>  u.id), :method => :delete %>
        
        <% elsif u.invited? current_user  %>
             
             <%= button_to "Accept", friendship_path(u,:user_id => u.id), :method => :put %>
             <%= button_to "Decline", friendship_path(u, :user_id =>  u.id), :method => :delete %>

        <% else %>
             
             <%= button_to "Add Friend", friendships_path( :user_id =>  u), :method => :post %>
        
        <% end %>
      <% end %>
    <% end %>
         </td>
      </tr>

      

    <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1>new user</h1>

    <%= render 'form' %>

  </div>
</div>